version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: pizzashop-postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=pizzashop
    volumes:
      - pizzashop_postgres_data:/bitnami/postgresql

volumes:
  pizzashop_postgres_data:
